In [ ]:
import pandas as pd

movies = pd.read_csv(
    'C:\Users\omark\OneDrive\سطح المكتب\Level 4\Information Retrieval\Project\Deployment\tmdb_5000_movies.csv'
)

credits = pd.read_csv(
    'C:\Users\omark\OneDrive\سطح المكتب\Level 4\Information Retrieval\Project\Deployment\tmdb_5000_credits.csv'
)

movies = movies.merge(
    credits,
    left_on='id',
    right_on='movie_id'
)

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,movie_id,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [4]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_x', 'vote_average',
       'vote_count', 'movie_id', 'title_y', 'cast', 'crew'],
      dtype='object')

In [5]:
# التحقق إن id == movie_id

print(
    (movies['id'] == movies['movie_id']).all()
)

True

In [6]:
movies.sample(19)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,movie_id,title_y,cast,crew
4304,1250000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 35, ""name...",http://www.bluelikejazzthemovie.com/,98369,"[{""id"": 155851, ""name"": ""book store""}]",en,Blue Like Jazz,A young man must find his own way as his South...,1.611600,"[{""name"": ""Ruckus Films"", ""id"": 36108}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Everybody belongs somewhere,Blue Like Jazz,5.8,25,98369,Blue Like Jazz,"[{""cast_id"": 1, ""character"": ""Donald Miller"", ...","[{""credit_id"": ""56194d8192514155d200011e"", ""de..."
3004,10000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 35, ""na...",http://www.dogma-movie.com/,1832,"[{""id"": 290, ""name"": ""angel""}, {""id"": 2024, ""n...",en,Dogma,The latest battle in the eternal war between G...,14.543435,"[{""name"": ""Lions Gate"", ""id"": 6644}, {""name"": ...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,It can be Hell getting into Heaven,Dogma,6.8,823,1832,Dogma,"[{""cast_id"": 1, ""character"": ""Bartleby"", ""cred...","[{""credit_id"": ""52fe4318c3a36847f8039ec1"", ""de..."
1371,35000000,"[{""id"": 35, ""name"": ""Comedy""}]",NaN,271718,"[{""id"": 567, ""name"": ""alcohol""}, {""id"": 2864, ...",en,Trainwreck,Having thought that monogamy was never possibl...,72.774941,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,We All Know One.,Trainwreck,5.9,1181,271718,Trainwreck,"[{""cast_id"": 4, ""character"": ""Amy Townsend"", ""...","[{""credit_id"": ""55aa7f0c92514172ef003b26"", ""de..."
4002,2600000,"[{""id"": 99, ""name"": ""Documentary""}]",http://www.sonyclassics.com/ridinggiants/,291,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 387, ""na...",en,Riding Giants,Riding Giants is story about big wave surfers ...,0.895946,[],...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Riding Giants,7.6,23,291,Riding Giants,"[{""cast_id"": 4, ""character"": ""Jeff Clark"", ""cr...","[{""credit_id"": ""52fe4233c3a36847f800b9f9"", ""de..."
241,135000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",http://www.teenagemutantninjaturtlesmovie.com/,308531,"[{""id"": 380, ""name"": ""brother brother relation...",en,Teenage Mutant Ninja Turtles: Out of the Shadows,"After supervillain Shredder escapes custody, h...",39.873791,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Raise some shell.,Teenage Mutant Ninja Turtles: Out of the Shadows,5.8,963,308531,Teenage Mutant Ninja Turtles: Out of the Shadows,"[{""cast_id"": 3, ""character"": ""April O'Neil"", ""...","[{""credit_id"": ""551b8ef6c3a3687682001b51"", ""de..."
506,76000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 35, ""...",http://www.despicableme.com/,93456,"[{""id"": 4289, ""name"": ""secret agent""}, {""id"": ...",en,Despicable Me 2,Gru is recruited by the Anti-Villain League to...,136.886704,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Back 2 Work,Despicable Me 2,7.0,4637,93456,Despicable Me 2,"[{""cast_id"": 11, ""character"": ""Gru (voice)"", ""...","[{""credit_id"": ""52fe492c9251416c750bfc79"", ""de..."
3590,5000000,"[{""id"": 36, ""name"": ""History""}, {""id"": 18, ""na...",NaN,24973,"[{""id"": 1160, ""name"": ""egypt""}]",en,The Egyptian,"In eighteenth-dynasty Egypt, Sinuhe, a poor or...",4.079111,"[{""name"": ""Twentieth Century Fox Film Corporat...",...,"[{""iso_639_1"": ""el"", ""name"": ""\u03b5\u03bb\u03...",Released,"To Nefer, shameless temptress of Babylon, he s...",The Egyptian,6.0,11,24973,The Egyptian,"[{""cast_id"": 1, ""character"": ""Merit"", ""credit_...","[{""credit_id"": ""572653a99251413309003825"", ""de..."
4282,1250000,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 53, ""nam...",NaN,9725,"[{""id"": 1890, ""name"": ""camping""}, {""id"": 5767,...",en,Friday the 13th Part 2,Five years after the horrible bloodbath at Cam...,16.517777,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The body count continues...,Friday the 13th Part 2,6.0,315,9725,Friday the 13th Part 2,"[{""cast_id"": 1, ""character"": ""Ginny Field"", ""c...","[{""credit_id"": ""52fe4522c3a36847f80be597"", ""de..."
4244,1200000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 36, ""name...",http://www3.amigomovie.com/,72913,"[{""id"": 502, ""name"": ""ambush""}, {""id"": 526, ""n...",en,Amigo,"Rafael, a village mayor caught in the murderou...",0.193172,"[{""name"": ""Anarchist's Convention Films"", ""id""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Amigo,6.0,2,72913,Amigo,"[{""cast_id"": 3, ""character"": ""Col. Hardacre"", ...","[{""credit_id"": ""52fe4884c3a368484e0fcd99"", ""de..."
3171,9000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 12, ""nam...",NaN,11282,"[{""id"": 380, ""name"": ""brother brother relation...",en,Harold & Kumar Go to White Castle,"Sometimes, it takes a strange night to put eve...",18.514292,"[{""name"": ""New Line Cinema"", ""id"": 12}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Fast Food. High Times.,Harold & Kumar Go to White Castle,6.6,693,11282,Harold & Kumar Go to White Castle,"[{""cast_id"": 1, ""character"": ""Harold Lee"", ""cr...","[{""credit_id"": ""563474569251414ab70150db"", ""de..."
850,50000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 18, ""nam...",NaN,12123,"[{""id"": 1812, ""name"": ""fbi""}, {""id"": 2528, ""na...",en,Chain Reaction,Two researchers in a green alternative energy ...,20.588620,"[{""name"": ""Twentieth Century Fox Film Corporat...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Reaction Time 8-4-96,Chain Reaction,5.3,284,12123,Chain Reaction,"[{""cast_id"": 14, ""character"": ""Eddie Kasalivic...","[{""credit_id"": ""52fe44ba9251416c7503ee1d"", ""de..."
3943,3000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",http://genvideoshd.com/watch-compadres-2016-fu...,317930,[],es,Compadres,A disgruntled Mexican cop is forced to work wi...,1.569246,[],...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Compadres,5.2,17,317930,Compadres,"[{""cast_id"": 3, ""character"": """", ""credit_id"": ...","[{""credit_id"": ""54b5c112c3a36838d500034b"", ""de..."
1823,30000000,"[{""id"": 27, ""name"": ""Horror""}]",NaN,6466,"[{""id"": 9826, ""name"": ""murder""}, {""id"": 10776,...",en,Freddy vs. Jason,Evil dream-demon Freddy Krueger devises a plan...,26.695920,"[{""name"": ""New Line Cinema"", ""id"": 12}, {""name...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Evil Will Battle Evil,Freddy vs. Jason,5.8,594,6466,Freddy vs. Jason,"[{""cast_id"": 1, ""character"": ""Freddy Krueger"",...","[{""credit_id"": ""551d04719251416a23002293"", ""de..."
272,90000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,24113,"[{""id"": 2301, ""name"": ""architect""}, {""id"": 345...",en,Town & Country,Porter Stoddard is a well-known New York archi...,1.004579,"[{""name"": ""New Line Cinema"", ""id"": 12}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,There's no such thing as a small affair.,Town & Country,3.7,16,24113,Town & Country,"[{""cast_id"": 3, ""character"": ""Porter Stoddard""...","[{""credit_id"": ""52fe4483c3a368484e02742d"", ""de..."
1933,0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",NaN,19803,"[{""id"": 6149, ""name"": ""police""}, {""id"": 6270, ...",en,Underclassman,A young detective goes undercover at an elite ...,2.083856,"[{""name"": ""Miramax Films"", ""id"": 14}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Underclassman,5.5,28,19803,Underclassman,"[{""cast_id"": 1, ""character"": ""Tracy 'Tre' Stok...","[{""credit_id"": ""56480a3e9251413ae1005bbc"", ""de..."
2344,18000000,"[{""id"": 18, ""name"": ""Drama""}]",NaN,1578,"[{""id"": 396, ""name"": ""transporter""}, {""id"": 93...",en,Raging Bull,When Jake LaMotta steps into a boxing ring and...,35.524457,"[{""name"": ""United Artists"", ""id"": 60}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Raging Bull,7.7,938,1578,Raging Bull,"[{""cast_id"": 1, ""character"": ""Jake La Motta"", ...","[{""credit_id"": ""52fe4300c3a36847f8032f25"", ""de..."
1793,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,1901,"[{""id"": 1599, ""name"": ""midlife crisis""}, {""id""...",en,In Good Company,Dan Foreman is a seasoned advertisement sales ...,15.376391,"[{""name"": ""Depth of Field"", ""id"": 1473}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,"He's rich, young and handsome. He's in love wi...",In Good Company,5.9,194,1901,In Good Company,"[{""cast_id"": 1, ""character"": ""Carter Duryea"", ...","[{""credit_id"": ""52fe431fc3a36847f803c207"", ""de..."
3400,0,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 53, ""name...",NaN,277519,[],cn,Z 風暴,This is a story about the biggest financial fr...,0.542814,"[{""name"": ""Pegasus Motion Pictures"", ""id"": 6950}]",...,"[{""iso_639_1"": ""cn"", ""name"": ""\u5e7f\u5dde\u8b...",Released,NaN,Z Storm,5.8,5,277519,Z Storm,"[{""cast_id"": 0, ""character"": ""William Luk"", ""c...","[{""credit_id"": ""53ad797c0e0a265975002134"", ""de..."
3160,10000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10402, ""n...",NaN,27586,"[{""id"": 515, ""name"": ""women""}, {""id"": 1228, ""n...",en,The Runaways,"Joan Jett and Cherie Currie, two rebellious te...",17.611971,"[{""name"": ""River Road Entertainment"", ""id"": 12...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,It's 1975 and they're about to explode.,The Runaways,6.3,254,27586,The Runaways,"[{""cast_id"": 4, ""character"": ""Cherie Currie"", ...","[{""credit_id"": ""52fe4556c3a368484e0545ad"", ""de..."

In [7]:
movies.drop(
    columns=['movie_id'],
    inplace=True
)

In [8]:
print(
    (movies['title_x'] == movies['title_y']).all()
)

True

In [9]:
movies.drop(
    columns=['title_y'],
    inplace=True
)

movies.rename(
    columns={
        'title_x': 'title'
    },
    inplace=True
)

In [10]:
import ast

def clean_crew(text):

    names = []

    try:

        crew_list = ast.literal_eval(text)

        for item in crew_list:

            # خد الـ Director فقط
            if item['job'] == 'Director':

                names.append(
                    item['name']
                )

    except:
        pass

    return " ".join(names)

In [11]:
movies['director'] = movies[
    'crew'
].apply(clean_crew)

In [12]:
movies[['crew', 'director']].head()

                                                crew           director
0  [{"credit_id": "52fe48009251416c750aca23", "de...      James Cameron
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...     Gore Verbinski
2  [{"credit_id": "54805967c3a36829b5002c41", "de...         Sam Mendes
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  Christopher Nolan
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...     Andrew Stanton

In [13]:
import ast

def clean_languages(text):

    names = []

    try:

        lang_list = ast.literal_eval(text)

        for item in lang_list:

            names.append(
                item['name']
            )

    except:
        pass

    return " ".join(names)

In [14]:
movies['spoken_languages_clean'] = movies[
    'spoken_languages'
].apply(clean_languages)

In [15]:
movies[[
    'spoken_languages',
    'spoken_languages_clean'
]].head()

,spoken_languages,spoken_languages_clean
0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",English Español
1,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",English
2,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Français English Español Italiano Deutsch
3,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",English
4,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",English

In [16]:
import ast

def clean_genres(text):

    names = []

    try:

        genres_list = ast.literal_eval(text)

        for item in genres_list:

            names.append(
                item['name']
            )

    except:
        pass

    return " ".join(names)

In [17]:
movies['genres_clean'] = movies[
    'genres'
].apply(clean_genres)

In [18]:
movies[[
    'genres',
    'genres_clean'
]].head()

,genres,genres_clean
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Action Adventure Fantasy Science Fiction
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",Adventure Fantasy Action
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Action Adventure Crime
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Action Crime Drama Thriller
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Action Adventure Science Fiction

In [19]:
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,status,tagline,title,vote_average,vote_count,cast,crew,director,spoken_languages_clean,genres_clean
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,Released,Enter the World of Pandora.,Avatar,7.2,11800,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",James Cameron,English Español,Action Adventure Fantasy Science Fiction
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",Gore Verbinski,English,Adventure Fantasy Action
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,Released,A Plan No One Escapes,Spectre,6.3,4466,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",Sam Mendes,Français English Español Italiano Deutsch,Action Adventure Crime
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,Released,The Legend Ends,The Dark Knight Rises,7.6,9106,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",Christopher Nolan,English,Action Crime Drama Thriller
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,Released,"Lost in our world, found in another.",John Carter,6.1,2124,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",Andrew Stanton,English,Action Adventure Science Fiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de...",Robert Rodriguez,Español,Action Crime Thriller
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de...",Edward Burns,,Comedy Romance
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,Released,NaN,"Signed, Sealed, Delivered",7.0,6,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de...",Scott Smith,English,Comedy Drama Romance TV Movie
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",Daniel Hsia,English,
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,Released,NaN,My Date with Drew,6.3,16,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de...",Brian Herzlinger Jon Gunn Brett Winn,English,Documentary

In [20]:
import ast

def clean_cast(text):

    names = []

    try:

        cast_list = ast.literal_eval(text)

        # أول 5 ممثلين فقط
        for item in cast_list[:5]:

            names.append(
                item['name']
            )

    except:
        pass

    return " ".join(names)

In [21]:
movies['main_cast'] = movies[
    'cast'
].apply(clean_cast)

In [22]:
movies[[
    'cast',
    'main_cast'
]].head()

,cast,main_cast
0,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",Sam Worthington Zoe Saldana Sigourney Weaver S...
1,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",Johnny Depp Orlando Bloom Keira Knightley Stel...
2,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",Daniel Craig Christoph Waltz Léa Seydoux Ralph...
3,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",Christian Bale Michael Caine Gary Oldman Anne ...
4,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",Taylor Kitsch Lynn Collins Samantha Morton Wil...

In [23]:
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,tagline,title,vote_average,vote_count,cast,crew,director,spoken_languages_clean,genres_clean,main_cast
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,Enter the World of Pandora.,Avatar,7.2,11800,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",James Cameron,English Español,Action Adventure Fantasy Science Fiction,Sam Worthington Zoe Saldana Sigourney Weaver S...
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",Gore Verbinski,English,Adventure Fantasy Action,Johnny Depp Orlando Bloom Keira Knightley Stel...
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,A Plan No One Escapes,Spectre,6.3,4466,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",Sam Mendes,Français English Español Italiano Deutsch,Action Adventure Crime,Daniel Craig Christoph Waltz Léa Seydoux Ralph...
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,The Legend Ends,The Dark Knight Rises,7.6,9106,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",Christopher Nolan,English,Action Crime Drama Thriller,Christian Bale Michael Caine Gary Oldman Anne ...
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,"Lost in our world, found in another.",John Carter,6.1,2124,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",Andrew Stanton,English,Action Adventure Science Fiction,Taylor Kitsch Lynn Collins Samantha Morton Wil...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de...",Robert Rodriguez,Español,Action Crime Thriller,Carlos Gallardo Jaime de Hoyos Peter Marquardt...
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de...",Edward Burns,,Comedy Romance,Edward Burns Kerry Bishé Marsha Dietlein Caitl...
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,NaN,"Signed, Sealed, Delivered",7.0,6,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de...",Scott Smith,English,Comedy Drama Romance TV Movie,Eric Mabius Kristin Booth Crystal Lowe Geoff G...
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,A New Yorker in Shanghai,Shanghai Calling,5.7,7,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",Daniel Hsia,English,,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,NaN,My Date with Drew,6.3,16,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de...",Brian Herzlinger Jon Gunn Brett Winn,English,Documentary,Drew Barrymore Brian Herzlinger Corey Feldman ...

In [24]:
import ast

def clean_keywords(text):

    names = []

    try:

        keywords_list = ast.literal_eval(text)

        for item in keywords_list:

            names.append(
                item['name']
            )

    except:
        pass

    return " ".join(names)

In [25]:
movies['keywords_clean'] = movies[
    'keywords'
].apply(clean_keywords)

In [26]:
movies[[

    'keywords',
    'keywords_clean'
]].head()

,keywords,keywords_clean
0,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",culture clash future space war space colony so...
1,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",ocean drug abuse exotic island east india trad...
2,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",spy based on novel secret agent sequel mi6 bri...
3,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",dc comics crime fighter terrorist secret ident...
4,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",based on novel mars medallion space travel pri...

In [27]:
movies['tags'] = (
    movies['title'].fillna('') + ' ' +
    movies['overview'].fillna('') + ' ' +
    movies['genres_clean'].fillna('') + ' ' +
    movies['keywords_clean'].fillna('') + ' ' +
    movies['main_cast'].fillna('') + ' ' +
    movies['director'].fillna('') + ' ' +
    movies['spoken_languages_clean'].fillna('')
)

In [28]:
movies['tags']

0       Avatar In the 22nd century, a paraplegic Marin...
1       Pirates of the Caribbean: At World's End Capta...
2       Spectre A cryptic message from Bond’s past sen...
3       The Dark Knight Rises Following the death of D...
4       John Carter John Carter is a war-weary, former...
                              ...
4798    El Mariachi El Mariachi just wants to play his...
4799    Newlyweds A newlywed couple's honeymoon is upe...
4800    Signed, Sealed, Delivered "Signed, Sealed, Del...
4801    Shanghai Calling When ambitious New York attor...
4802    My Date with Drew Ever since the second grade ...
Name: tags, Length: 4803, dtype: object

In [29]:
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(
    stopwords.words('english')
)

lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [30]:
def preprocess(text):

    text = str(text).lower()

    # remove special chars
    text = re.sub(
        r'[^a-zA-Z0-9 ]',
        ' ',
        text
    )

    # tokenize
    words = text.split()

    # remove stopwords
    words = [
        w for w in words
        if w not in stop_words
    ]

    # lemmatization
    words = [
        lemmatizer.lemmatize(w)
        for w in words
    ]

    return " ".join(words)

In [31]:
def preprocess_title(text):

    text = str(text).lower()

    # remove special chars only
    text = re.sub(
        r'[^a-zA-Z0-9 ]',
        ' ',
        text
    )

    return text

In [32]:
movies['clean_title'] = movies[
    'title'
].apply(preprocess_title)

In [33]:
movies['clean_overview'] = movies[
    'overview'
].apply(preprocess)

In [34]:
movies[[
    'title',
    'clean_title',
    'overview',
    'clean_overview'
]].head()

,title,clean_title,overview,clean_overview
0,Avatar,avatar,"In the 22nd century, a paraplegic Marine is di...",22nd century paraplegic marine dispatched moon...
1,Pirates of the Caribbean: At World's End,pirates of the caribbean at world s end,"Captain Barbossa, long believed to be dead, ha...",captain barbossa long believed dead come back ...
2,Spectre,spectre,A cryptic message from Bond’s past sends him o...,cryptic message bond past sends trail uncover ...
3,The Dark Knight Rises,the dark knight rises,Following the death of District Attorney Harve...,following death district attorney harvey dent ...
4,John Carter,john carter,"John Carter is a war-weary, former military ca...",john carter war weary former military captain ...

In [35]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'cast', 'crew', 'director', 'spoken_languages_clean',
       'genres_clean', 'main_cast', 'keywords_clean', 'tags', 'clean_title',
       'clean_overview'],
      dtype='object')

In [36]:
movies = movies[[
    'id',
    'title',
    'overview',
    'genres_clean',
    'keywords_clean',
    'main_cast',
    'director',
    'spoken_languages_clean',
    'popularity',
    'vote_average',
    'clean_title',
    'clean_overview'
]]

In [37]:
movies.head()

,id,title,overview,genres_clean,keywords_clean,main_cast,director,spoken_languages_clean,popularity,vote_average,clean_title,clean_overview
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...,Sam Worthington Zoe Saldana Sigourney Weaver S...,James Cameron,English Español,150.437577,7.2,avatar,22nd century paraplegic marine dispatched moon...
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,ocean drug abuse exotic island east india trad...,Johnny Depp Orlando Bloom Keira Knightley Stel...,Gore Verbinski,English,139.082615,6.9,pirates of the caribbean at world s end,captain barbossa long believed dead come back ...
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,spy based on novel secret agent sequel mi6 bri...,Daniel Craig Christoph Waltz Léa Seydoux Ralph...,Sam Mendes,Français English Español Italiano Deutsch,107.376788,6.3,spectre,cryptic message bond past sends trail uncover ...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,dc comics crime fighter terrorist secret ident...,Christian Bale Michael Caine Gary Oldman Anne ...,Christopher Nolan,English,112.312950,7.6,the dark knight rises,following death district attorney harvey dent ...
4,49529,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure Science Fiction,based on novel mars medallion space travel pri...,Taylor Kitsch Lynn Collins Samantha Morton Wil...,Andrew Stanton,English,43.926995,6.1,john carter,john carter war weary former military captain ...

In [39]:
movies.duplicated().sum()

np.int64(0)

In [40]:
movies.isnull().sum()

id                        0
title                     0
overview                  3
genres_clean              0
keywords_clean            0
main_cast                 0
director                  0
spoken_languages_clean    0
popularity                0
vote_average              0
clean_title               0
clean_overview            0
dtype: int64

In [41]:
movies['overview'] = movies[
    'overview'
].fillna('')

/tmp/ipykernel_1788/2798227457.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['overview'] = movies[

#Inverted Index

In [42]:
from collections import defaultdict

In [43]:
inverted_index = {
    'title': defaultdict(list),
    'overview': defaultdict(list)
}

In [44]:
for idx, row in movies.iterrows():

    tokens = row['clean_title'].split()

    for token in tokens:

        inverted_index['title'][token].append(idx)

In [45]:
for idx, row in movies.iterrows():

    tokens = row['clean_overview'].split()

    for token in tokens:

        inverted_index['overview'][token].append(idx)

In [46]:
inverted_index['title']['avatar']

[0]

In [47]:
inverted_index['overview']['space'][:10]

[27, 52, 56, 57, 67, 87, 95, 149, 222, 239]

In [49]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [69]:
movies['clean_cast'] = movies[
    'main_cast'
].apply(preprocess_title)

/tmp/ipykernel_1788/1387420255.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['clean_cast'] = movies[

In [70]:
movies['clean_director'] = movies[
    'director'
].apply(preprocess_title)

/tmp/ipykernel_1788/2449885211.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['clean_director'] = movies[

In [87]:
title_vectorizer = TfidfVectorizer(
    ngram_range=(1,2)
)

title_matrix = title_vectorizer.fit_transform(
    movies['clean_title']
)

In [88]:
overview_vectorizer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2)
)

overview_matrix = overview_vectorizer.fit_transform(
    movies['clean_overview']
)

In [89]:
cast_vectorizer = TfidfVectorizer(
    ngram_range=(1,2)
)

cast_matrix = cast_vectorizer.fit_transform(
    movies['clean_cast']
)

In [90]:
director_vectorizer = TfidfVectorizer(
    ngram_range=(1,2)
)

director_matrix = director_vectorizer.fit_transform(
    movies['clean_director']
)

In [91]:
from sklearn.metrics.pairwise import cosine_similarity

In [92]:
def search_movies(
    query,
    title_weight=2.0,
    overview_weight=1.0,
    cast_weight=1.5,
    director_weight=1.5,
    top_k=10
):

    # =========================
    # preprocess query
    # =========================

    clean_query_title = preprocess_title(query)

    clean_query_overview = preprocess(query)

    # =========================
    # title similarity
    # =========================

    title_query_vector = title_vectorizer.transform(
        [clean_query_title]
    )

    title_scores = cosine_similarity(
        title_query_vector,
        title_matrix
    ).flatten()

    # =========================
    # overview similarity
    # =========================

    overview_query_vector = overview_vectorizer.transform(
        [clean_query_overview]
    )

    overview_scores = cosine_similarity(
        overview_query_vector,
        overview_matrix
    ).flatten()

    # =========================
    # cast similarity
    # =========================

    cast_query_vector = cast_vectorizer.transform(
        [clean_query_title]
    )

    cast_scores = cosine_similarity(
        cast_query_vector,
        cast_matrix
    ).flatten()

    # =========================
    # director similarity
    # =========================

    director_query_vector = director_vectorizer.transform(
        [clean_query_title]
    )

    director_scores = cosine_similarity(
        director_query_vector,
        director_matrix
    ).flatten()

    # =========================
    # final weighted score
    # =========================

    final_scores = (
        title_weight * title_scores
        +
        overview_weight * overview_scores
        +
        cast_weight * cast_scores
        +
        director_weight * director_scores
    )

    # =========================
    # top results
    # =========================

    top_indices = final_scores.argsort()[-top_k:][::-1]

    results = movies.iloc[top_indices][[
        'title',
        'genres_clean',
        'main_cast',
        'director',
        'vote_average',
        'popularity'
    ]]

    results['score'] = final_scores[top_indices]

    return results

In [97]:
search_movies(
    "spider",
    cast_weight=5.0
)

,title,genres_clean,main_cast,director,vote_average,popularity,score
3085,Spider,Drama Mystery Thriller,Ralph Fiennes Miranda Richardson Gabriel Byrne...,David Cronenberg,6.4,6.948401,2.000000
5,Spider-Man 3,Fantasy Action Adventure,Tobey Maguire Kirsten Dunst James Franco Thoma...,Sam Raimi,5.9,115.699814,1.680869
159,Spider-Man,Fantasy Action,Tobey Maguire Willem Dafoe Kirsten Dunst James...,Sam Raimi,6.8,82.502566,1.586242
30,Spider-Man 2,Action Adventure Fantasy,Tobey Maguire Kirsten Dunst James Franco Alfre...,Sam Raimi,6.7,35.149586,1.449544
1699,Along Came a Spider,Crime Mystery Thriller Action,Morgan Freeman Monica Potter Michael Wincott D...,Lee Tamahori,6.1,21.252797,1.025732
38,The Amazing Spider-Man 2,Action Adventure Fantasy,Andrew Garfield Emma Stone Jamie Foxx Dane DeH...,Marc Webb,6.5,89.270217,0.953532
20,The Amazing Spider-Man,Action Adventure Fantasy,Andrew Garfield Emma Stone Rhys Ifans Denis Le...,Marc Webb,6.5,89.866276,0.943657
1534,Arachnophobia,Comedy Horror,Jeff Daniels Harley Jane Kozak Garette Ratliff...,Frank Marshall,6.2,15.895661,0.663861
3129,Jungle Shuffle,Family Animation Adventure,Drake Bell Rob Schneider Brianne Siddall Joey ...,Taedong Park Mauricio De la Orta,6.5,1.413934,0.301717
3383,Losin' It,Comedy,Tom Cruise Jackie Earle Haley John Stockwell J...,Curtis Hanson,4.5,2.550045,0.255626

In [96]:
search_movies(
    "spider"

)

,title,genres_clean,main_cast,director,vote_average,popularity,score
3085,Spider,Drama Mystery Thriller,Ralph Fiennes Miranda Richardson Gabriel Byrne...,David Cronenberg,6.4,6.948401,2.000000
5,Spider-Man 3,Fantasy Action Adventure,Tobey Maguire Kirsten Dunst James Franco Thoma...,Sam Raimi,5.9,115.699814,1.680869
159,Spider-Man,Fantasy Action,Tobey Maguire Willem Dafoe Kirsten Dunst James...,Sam Raimi,6.8,82.502566,1.586242
30,Spider-Man 2,Action Adventure Fantasy,Tobey Maguire Kirsten Dunst James Franco Alfre...,Sam Raimi,6.7,35.149586,1.449544
1699,Along Came a Spider,Crime Mystery Thriller Action,Morgan Freeman Monica Potter Michael Wincott D...,Lee Tamahori,6.1,21.252797,1.025732
38,The Amazing Spider-Man 2,Action Adventure Fantasy,Andrew Garfield Emma Stone Jamie Foxx Dane DeH...,Marc Webb,6.5,89.270217,0.953532
20,The Amazing Spider-Man,Action Adventure Fantasy,Andrew Garfield Emma Stone Rhys Ifans Denis Le...,Marc Webb,6.5,89.866276,0.943657
1534,Arachnophobia,Comedy Horror,Jeff Daniels Harley Jane Kozak Garette Ratliff...,Frank Marshall,6.2,15.895661,0.663861
3129,Jungle Shuffle,Family Animation Adventure,Drake Bell Rob Schneider Brianne Siddall Joey ...,Taedong Park Mauricio De la Orta,6.5,1.413934,0.301717
3383,Losin' It,Comedy,Tom Cruise Jackie Earle Haley John Stockwell J...,Curtis Hanson,4.5,2.550045,0.255626

In [71]:
movies

,id,title,overview,genres_clean,keywords_clean,main_cast,director,spoken_languages_clean,popularity,vote_average,clean_title,clean_overview,clean_cast,clean_director
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...,Sam Worthington Zoe Saldana Sigourney Weaver S...,James Cameron,English Español,150.437577,7.2,avatar,22nd century paraplegic marine dispatched moon...,sam worthington zoe saldana sigourney weaver s...,james cameron
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,ocean drug abuse exotic island east india trad...,Johnny Depp Orlando Bloom Keira Knightley Stel...,Gore Verbinski,English,139.082615,6.9,pirates of the caribbean at world s end,captain barbossa long believed dead come back ...,johnny depp orlando bloom keira knightley stel...,gore verbinski
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,spy based on novel secret agent sequel mi6 bri...,Daniel Craig Christoph Waltz Léa Seydoux Ralph...,Sam Mendes,Français English Español Italiano Deutsch,107.376788,6.3,spectre,cryptic message bond past sends trail uncover ...,daniel craig christoph waltz l a seydoux ralph...,sam mendes
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,dc comics crime fighter terrorist secret ident...,Christian Bale Michael Caine Gary Oldman Anne ...,Christopher Nolan,English,112.312950,7.6,the dark knight rises,following death district attorney harvey dent ...,christian bale michael caine gary oldman anne ...,christopher nolan
4,49529,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure Science Fiction,based on novel mars medallion space travel pri...,Taylor Kitsch Lynn Collins Samantha Morton Wil...,Andrew Stanton,English,43.926995,6.1,john carter,john carter war weary former military captain ...,taylor kitsch lynn collins samantha morton wil...,andrew stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,Action Crime Thriller,united states–mexico barrier legs arms paper k...,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,Robert Rodriguez,Español,14.269792,6.6,el mariachi,el mariachi want play guitar carry family trad...,carlos gallardo jaime de hoyos peter marquardt...,robert rodriguez
4799,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,Comedy Romance,,Edward Burns Kerry Bishé Marsha Dietlein Caitl...,Edward Burns,,0.642552,5.9,newlyweds,newlywed couple honeymoon upended arrival resp...,edward burns kerry bish marsha dietlein caitl...,edward burns
4800,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",Comedy Drama Romance TV Movie,date love at first sight narration investigati...,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,Scott Smith,English,1.444476,7.0,signed sealed delivered,signed sealed delivered introduces dedicated q...,eric mabius kristin booth crystal lowe geoff g...,scott smith
4801,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,,,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,Daniel Hsia,English,0.857008,5.7,shanghai calling,ambitious new york attorney sam sent shanghai ...,daniel henney eliza coupe bill paxton alan ruc...,daniel hsia
4802,25975,My Date with Drew,Ever since the second grade when he first saw ...,Documentary,obsession camcorder crush dream girl,Drew Barrymore Brian Herzlinger Corey Feldman ...,Brian Herzlinger Jon Gunn Brett Winn,English,1.929883,6.3,my date with drew,ever since second grade first saw e extraterre...,drew barrymore brian herzlinger corey feldman ...,brian herzlinger jon gunn brett winn

In [73]:
movies.columns

Index(['id', 'title', 'overview', 'genres_clean', 'keywords_clean',
       'main_cast', 'director', 'spoken_languages_clean', 'popularity',
       'vote_average', 'clean_title', 'clean_overview', 'clean_cast',
       'clean_director'],
      dtype='object')

#BM25

In [98]:
!pip install rank-bm25

Collecting rank-bm25
  Downloading rank_bm25-0.2.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rank-bm25) (2.0.2)
Downloading rank_bm25-0.2.2-py3-none-any.whl (8.6 kB)
Installing collected packages: rank-bm25
Successfully installed rank-bm25-0.2.2

In [99]:
from rank_bm25 import BM25Okapi

In [100]:
movies['bm25_text'] = (
    movies['clean_title'] + ' ' +
    movies['clean_overview'] + ' ' +
    movies['clean_cast'] + ' ' +
    movies['clean_director']
)

/tmp/ipykernel_1788/140148228.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['bm25_text'] = (

In [101]:
tokenized_corpus = [
    doc.split()
    for doc in movies['bm25_text']
]

In [102]:
bm25 = BM25Okapi(
    tokenized_corpus
)

In [124]:
def bm25_search(
    query,
    top_k=10
):

    # preprocess query
    clean_query = preprocess(query)

    # tokenize query
    tokenized_query = clean_query.split()

    # BM25 scores
    scores = bm25.get_scores(
        tokenized_query
    )

    # top results
    top_indices = scores.argsort()[-top_k:][::-1]

    results = movies.iloc[top_indices][[
        'title',
        'genres_clean',
        'main_cast',
        'director',
        'vote_average',
        'popularity'
    ]]

    results['score'] = scores[top_indices]
    results = results.sort_values(
    by=['score', 'popularity'],
    ascending=False
)

    return results

In [127]:
bm25_search(
    "dwayne johnson"
)

,title,genres_clean,main_cast,director,vote_average,popularity,score
1986,Faster,Crime Drama Action Thriller,Dwayne Johnson Billy Bob Thornton Maggie Grace...,"George Tillman, Jr.",6.1,26.324874,12.043145
44,Furious 7,Action,Vin Diesel Paul Walker Dwayne Johnson Michelle...,James Wan,7.3,102.322217,11.868455
914,Central Intelligence,Action Comedy,Dwayne Johnson Kevin Hart Amy Ryan Aaron Paul ...,Rawson Marshall Thurber,6.2,45.318703,11.434658
808,Walking Tall,Adventure Drama Action Thriller,Dwayne Johnson Johnny Knoxville Neal McDonough...,Kevin Bray,6.0,23.438398,11.434658
1615,Gridiron Gang,Action Adventure Crime Drama,Dwayne Johnson Xzibit L. Scott Caldwell Leon R...,Phil Joanou,6.5,9.278361,11.434658
244,San Andreas,Action Drama Thriller,Dwayne Johnson Alexandra Daddario Carla Gugino...,Brad Peyton,6.0,100.412364,10.903298
495,Journey 2: The Mysterious Island,Adventure Action Science Fiction,Dwayne Johnson Josh Hutcherson Kristin Davis V...,Brad Peyton,5.8,40.723459,10.903298
931,Race to Witch Mountain,Adventure Family Fantasy Science Fiction Thril...,Dwayne Johnson AnnaSophia Robb Alexander Ludwi...,Andy Fickman,5.5,23.935053,10.304732
166,G.I. Joe: Retaliation,Adventure Action Science Fiction Thriller,Dwayne Johnson D.J. Cotrona Adrianne Palicki B...,Jon M. Chu,5.4,59.325589,9.667841
715,The Scorpion King,Action Fantasy Adventure,Dwayne Johnson Kelly Hu Michael Clarke Duncan ...,Chuck Russell,5.3,37.537093,9.667841

#Evaluation

In [128]:
test_queries = {
    "brad pitt": [
        "Fight Club",
        "Se7en",
        "World War Z"
    ],

    "batman": [
        "Batman Begins",
        "The Dark Knight",
        "The Dark Knight Rises"
    ],

    "spider man": [
        "Spider-Man",
        "Spider-Man 2",
        "Spider-Man 3"
    ]
}

In [129]:
def precision_at_k(
    retrieved_titles,
    relevant_titles,
    k=10
):

    retrieved_k = retrieved_titles[:k]

    relevant_found = 0

    for movie in retrieved_k:

        if movie in relevant_titles:

            relevant_found += 1

    return relevant_found / k

In [130]:
for query, relevant_movies in test_queries.items():

    results = bm25_search(query)

    retrieved_titles = results[
        'title'
    ].tolist()

    precision = precision_at_k(
        retrieved_titles,
        relevant_movies,
        k=10
    )

    print(f"Query: {query}")

    print(f"Precision@10: {precision}")

    print("-" * 40)

Query: brad pitt
Precision@10: 0.0
----------------------------------------
Query: batman
Precision@10: 0.3
----------------------------------------
Query: spider man
Precision@10: 0.3
----------------------------------------